# Generated by Django 2.0.10 on 2019-02-08 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Richie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('locaction', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='jobs',
            name='creater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Richie'),
        ),
    ]
